[package]
name = "two_space"
version = "0.1.0"
authors = ["Matt Whelan <matt@blacklogik.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
